name: Test

on: 
  workflow_run:
    workflows: ["Train"]
    types:
      - completed
      - requested

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker image
      run: docker pull bhandar1994/myapp:${{ github.sha }}

    - name: Pull and Run Docker Image
      run: |
        score=$(docker run --rm bhandar1994/myapp:${{ github.sha }})
        if (( $(echo "$score > 0.25" | bc -l) )); then
          echo "Test passed"
        else
          echo "Test failed"
          exit 1
        fi
