name: Test

on: 
  workflow_run:
    workflows: ["Train"]
    types:
      - completed
      - requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Testing this step
        run: echo "The pull is success!"

      - name: Pull and Run the Docker Image 
        run: |
          score=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }})
          if (( $(echo "$score > 0.50" | bc -l) )); then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi
