name: Train

on:
  push:
    branches:
      - fail-both

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t Shridharbhandar/Shridhar_CI_CD_AIMLOps .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push Shridharbhandar/Shridhar_CI_CD_AIMLOps